[package]
name = "Av1an"
version = "0.1.0"
authors = ["Zen <46526140+master-of-zen@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "av1an_rust"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "*", features = ["extension-module"] }
