name: tests
on:
  push:
    paths-ignore:
      - "*.yml"
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.yml"
      - .gitignore
      - "*.md"

env:
  deps: python3-dev libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1-mesa-glx tree
  DEBIAN_FRONTEND: noninteractive

jobs:
  validate:
    name: ${{ matrix.enc }} ${{ matrix.test }}
    runs-on: ubuntu-latest
    container: registry.gitlab.com/luigi311/encoders-docker:latest
    strategy:
      fail-fast: false
      matrix:
        enc: [aom, rav1e, svt_av1, svt_vp9, vpx, x265, x264]
        test: [baseline, scenes, workers, chunk_hybrid, chunk_select, target_quality, vmaf, vmaf_plots, extra_splits, split_aom_keyframes]
        include:
          - test: baseline
            flags: ""
          - test: scenes
            flags: -s scenes.json
          - test: workers
            flags: -w 2
          - test: chunk_hybrid
            flags: --chunk_method hybrid
          - test: chunk_select
            flags: --chunk_method select
          - test: target_quality
            flags: --target_quality 95
          - test: vmaf
            flags: --vmaf
          - test: vmaf_plots
            flags: --vmaf_plots
          - test: extra_splits
            flags: -xs 10
          - test: split_aom_keyframes
            flags: --split_method aom_keyframes
          - test: video_settings
            enc: aom
            flags: -v " --cpu-used=3 --end-usage=q --cq-level=30 --threads=8 "
          - test: temp
            enc: aom
            flags: --temp temporary
    steps:
      - uses: actions/checkout@v2
      - name: Validate encoders
        run: |
          aomenc --help
          SvtAv1EncApp --help
          rav1e --help
          x265 --help || true
      - name: Install requirements
        run: |
          apt-get update && apt-get install -y ${{ env.deps }}
          pip3 install --no-cache-dir -r requirements.txt
      - name: Download videos
        run: |
          for url in raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master randomderp.com; do
            curl -LO https://$url/video.tar.gz && break
          done
          tar xf video.tar.gz
      - name: Testing ${{ matrix.name }}
        run: |
          ./av1an.py -i bus_cif.y4m -enc ${{ matrix.enc }} -tr 20 --keep -o "bus_cif.mkv" ${{ matrix.flags }}
          du -h bus_cif.mkv
          tree -a
